#!/bin/sh 
# 
# see: dh_installdeb(1) 
set -e 
USER=ldn 
PASS=ldn 
VHOST=/ldn 

case "$1" in 
	configure) 
		rabbitmqctl add_user $USER $PASS 
		rabbitmqctl add_vhost $VHOST 
		rabbitmqctl set_permissions -p $VHOST $USER "^$USER-.*" ".*" ".*" 
	;; 
	abort-upgrade|abort-remove|abort-deconfigure) exit 0;; 
esac 

exit 0